### ISSUE TITLE
getDOMNode vs findDOMNode

### ISSUE THREAD

**Issue by oliverwoodings** [QubitProducts/react-test-tree#16]
At some point the React team is going to deprecate getDOMNode. I don't think we should change test tree's API, however; we should keep the getDOMNode method and just be smarter internally about it. Therefore I propose we adjust our internal logic from this:

```js
  getDOMNode: function () {
    // support react-bootstrap elements
    if (this.element.getInputDOMNode) {
      return this.element.getInputDOMNode();
    }
    return this.element.getDOMNode();
  },
```
to this:

```js
  getDOMNode: function () {
    // support react-bootstrap elements
    if (this.element.getInputDOMNode) {
      return this.element.getInputDOMNode();
    } else if (React.findDOMNode) {
      return React.findDOMNode(this.element);
    } else {
      return this.element.getDOMNode();
    }
  },
```

@jhollingworth thoughts? Do we actually need to have backwards support for getDOMNode?

**Comment by oliverwoodings** [comment]
@jhollingworth bump

**Comment by jhollingworth** [comment]
sorry. forgot about this.

We don't need backwards compatibility, we should just track the latest

**Comment by oliverwoodings** [comment]
:+1: I'll just change it to do React.findDOMNode
