### ISSUE TITLE
Support react-bootstrap

### ISSUE THREAD

**Issue by jhollingworth** [QubitProducts/react-test-tree#2]
React Bootstrap components have a different api. I suggest we update [``getDOMNode``](https://github.com/QubitProducts/react-test-tree/blob/master/lib/testNode.js#L124-L126) to look like this

```js
getDOMNode: function () {
   // react-bootstrap makes input node accessible via getInputDOMNode
  if (this.element.getInputDOMNode) {
    return this.element.getInputDOMNode();
  }

  return this.element.getDOMNode();
},
```

**Comment by oliverwoodings** [comment]
Are there any other react bootstrap quirks we might need to account for?

**Comment by jhollingworth** [comment]
nah, thats it if I recall

**Comment by oliverwoodings** [comment]
Cool, will get it in the next version
