### ISSUE TITLE
babelify dependency

### ISSUE THREAD

**Issue by darkleaf** [QubitProducts/react-test-tree#23]
Hi!
Is this project **really** need babelify package as a production dependency?

PR by @oliverwoodings: [Fix babelify dependency. Add support for react-bootstrap](https://github.com/QubitProducts/react-test-tree/pull/4)

**Comment by oliverwoodings** [comment]
This was done to stop downstream projects using browserify throwing errors about babelify not being found. Actually I think we can avoid this entirely by just changing the test setup (since we don't need browserify for anything but testing). Thanks for pointing it out!

**Comment by oliverwoodings** [comment]
See #25

**Comment by darkleaf** [comment]
Thanks! :+1:
