### ISSUE TITLE
Unable to simulate keyDown

### ISSUE THREAD

**Issue by simax** [QubitProducts/react-test-tree#27]
Hi,

I have the following component:

```
var MyTestComponent = React.createClass({

  handleKeyDown(e) {
    if(e.keyCode === 27) {
      return this.handleAbandonChanges();
    }

    if(e.keyCode === 13) {
        e.preventDefault();
        this.handleAcceptChanges();
      }
    }
  },

  handleAbandonChanges() {
    // Code removed for brevity
  },

  handleAcceptChanges() {
    // Code removed for brevity
  },


  render() {
    return (
      <textarea
             ref='myinput'
             onKeyDown={this.handleKeyDown} />
    )
  }
});
```
 
Which works perfectly, but now I want to test it (and see coverage). So I write the following test.

```
describe("test-component", () => {

  it("Testing onChange", () => {

    let MyTestComponent = require('../test-component.jsx');

    let theComponent = testTree(<MyTestComponent />);
    let txtArea = theComponent.myinput;
    
    // I have to resort to using TestUtils.Simulate.keyDown
    let txtAreaNode = txtArea.getDOMNode();
    TestUtils.Simulate.keyDown(txtAreaNode, { keyCode: 27 });

    // Can't get the following working
    // txtAreaNode.simulate.keyDown(txtAreaNode, { keyCode: 27 });

  });
});

```

Which works and I can see that simulating the pressing of the ESCAPE key (keyCode 27) calls the ```handleAbandonChanges```. 

But I can't seem to make it work with ```node.simulate.keyDown ...``` I have to resort to using TestUtils.

Am I doing something wrong?

**Comment by oliverwoodings** [comment]
The simulate functions available on the node are already bound to the component, therefore you don't need to provide txtAreaNode as the first parameter. Instead you just do `txtAreaNode.simulate.keyDown({ keyCode: 27 })`

**Comment by simax** [comment]
OMG, I feel stupid now. Its even stated in the docs.

On another note, how could I test whether the handleAcceptChanges() method
was called or not. Should I be using something like sinon or is there a way
to do it via testTree ?

Thanks for your help,
Simon

**Comment by oliverwoodings** [comment]
@simax no worries, we all do it :smile:

**Comment by simax** [comment]
Oliver,

Did you see the second part of my reply? ....

How could I test whether the handleAcceptChanges() method was called or
not. Should I be using something like sinon or is there a way to do it via
testTree ?

Thanks for your help,
Simon

**Comment by oliverwoodings** [comment]
Just saw the other part of your question (Github cut it off)

testTree is designed purely to make react components more accessible for testing. What you are asking about there is more generic and not really related to React specifically, so it is not something testTree will ever do. I'd advise using sinon.

**Comment by simax** [comment]
Cool, thought so, just wanted to check.

Thanks for your help.
Simon
