### ISSUE TITLE
Please support all simulate methods

### ISSUE THREAD

**Issue by winkler1** [QubitProducts/react-test-tree#28]
Hi-
 I needed to doubleClick on a node, and ended up reaching into `TestUtils.Simulate.doubleClick` to do it.

Would be easier to remember and use if react-test-utils did everything TestUtils does. Found this programatic way to list all supported methods at http://qiita.com/kimagure/items/cf5200b0a2a516ca68f8:

```
'blur'
'click'
'contextMenu'
'copy'
'cut'
'doubleClick'
'drag'
'dragEnd'
'dragEnter'
'dragExit'
'dragLeave'
'dragOver'
'dragStart'
'drop'
'focus'
'input'
'keyDown'
'keyPress'
'keyUp'
'load'
'error'
'mouseDown'
'mouseMove'
'mouseOut'
'mouseOver'
'mouseUp'
'paste'
'reset'
'scroll'
'submit'
'touchCancel'
'touchEnd'
'touchMove'
'touchStart'
'wheel'
'mouseEnter'
'mouseLeave'
'change'
'compositionEnd'
'compositionStart'
'compositionUpdate'
'select'
```

**Comment by oliverwoodings** [comment]
It already supports all simulate methods. Please see the 'simulate' object
available on all nodes (as documented in the readme).

**Comment by winkler1** [comment]
Ah - so it does, thanks! Was confused because click() is handled differently.
