### ISSUE TITLE
How do you test Redux?

### ISSUE THREAD

**Issue by yanivtal** [QubitProducts/react-test-tree#40]
I noticed that you contributed to react-redux to make sure we can access the wrappedInstance of the connect HOC. How do you test your top level component that gets additionally wrapped by Provider?

In this example:
```
layout = Tree(
        <Provider store={getStore()} ref='provider'>
          {() => <Layout/>}
        </Provider>
      );
```

Without the Provider I can access the Layout component, but because it's wrapped in connect, it needs a Provider. How would you get access to the Layout component? Do you have a way of stubbing the store or do you reach down through the provider?

**Comment by oliverwoodings** [comment]
We recently released a new feature which should help with this. Check out the section on Higher Order Components in the README. You should be able to do something like so:

```jsx
Layout.innerComponentRef = 'wrappedInstance'
let layout = tree(
  <Provider store={getStore()}>
    {() => <Layout/>}
  </Provider>
);
```

`layout` will then be a reference to the test tree starting with your Layout component rather than the provider.

**Comment by yanivtal** [comment]
I set innerComponentRef to 'wrappedInstance' before exporting the Layout component but the layout object returned by tree isn't that rendered Layout component, it's the Provider. What do I do to get around the Provider?

**Comment by oliverwoodings** [comment]
Oh wait, I think I see your problem now. This is related to https://github.com/QubitProducts/react-test-tree/issues/36 about handling out-of-render refs (give it a read, should explain the situation you are running into). tl;dr of it, wrap your testing component in it's own component like so:
```jsx
var TestingComponent = React.createClass({
  render: function () {
    return (
      <Provider store={getStore()} ref='provider'>
        {() => <Layout ref='layout' />}
      </Provider>
    );
  }
});

var tree = tree(<TestingComponent />);
tree.layout;
tree.provider;
```

You could optionally combine this with the innerComponentRef stuff to exclude your testing component from the tree:

```jsx
var TestingComponent = React.createClass({
  render: function () {
    return (
      <Provider store={getStore()} ref='provider'>
        {() => <Layout ref='layout' />}
      </Provider>
    );
  }
});
TestingComponent.innerComponentRef = 'layout';

var layout = tree(<TestingComponent />);
```

**Comment by yanivtal** [comment]
Woo! It worked with tree.provider.layout. Thanks a ton! This project is fantastic. Making our tests real clean!

**Comment by oliverwoodings** [comment]
Out of interest, did you end up having to wrap it in a testing component?

**Comment by yanivtal** [comment]
Yes it didn't work without that trick. Thanks!

**Comment by oliverwoodings** [comment]
Hopefully once #36 is resolved you won't even need to do the wrapping, testTree will do it for you :)
