### ISSUE TITLE
SauceLabs Access Key Exposed

### ISSUE THREAD

**Issue by austinpray** [QubitProducts/react-test-tree#45]
Hey there!

Really enjoying this tool.

I wanted to point out that you have an unencrypted SauceLabs access key unencrypted. I believe this allows someone to run tests as you, which is bad because they could be running private tests which violate their ToS.

`travis encrypt SAUCE_ACCESS_KEY={{YOUR_KEY}}`

I noticed you are also parsing your .travis.yml in your karma config. This isn't necessary. You can see a working example here: https://github.com/UTD-CRSS/app.exploreapollo.org/blob/230ffab577ac1be155d72f72d048e01cae9e90b2/test/karma.config.js

Note: I'm not affiliated with SauceLabs, just something I noticed.

**Comment by oliverwoodings** [comment]
Hi @austinpray, thanks for this. I'll get this looked at soon.

**Comment by oliverwoodings** [comment]
Closed by #31
