### ISSUE TITLE
[1.0.0-rc1] node.get(refName) is returning more that it should and using stateless function component raises "Cannot read property '_reactInternalInstance' of null"

### ISSUE THREAD

**Issue by goncalvesjoao** [QubitProducts/react-test-tree#48]
Hi guys, I've made a simple use case to demonstrate these two problems, checkout it out: https://github.com/goncalvesjoao/rtt-test

Using react-test-tree 1.0.0-rc1 I'm able to test the first approach but not the other two.

The first example src/components/Droids, test/components/DroidsSpec is green, no problems there.

The second example src/components/DroidsWithRestProps, test/components/DroidsWithRestPropsSpec fails due to "droids.get('droids').length" that is counting 6 refs instead of just 2. This happens because the src/components/Droid is passing { ...this.props } to its children.

The third example src/components/DroidsWithStatelessComponen, test/components/DroidsWithStatelessComponentSpec fails because src/components/Droid is a stateless function component.

If this is not something new to you guys, feel free to close this issue. Looking forward for your next release, love this tool!
Thanks guys.

**Comment by oliverwoodings** [comment]
Thanks for this! Really helpful :)

DroidsWithRestProps - you are correct in that this is caused by props being passed to children. The root cause of this is because rtt assigns a unique an __rttId to each element, however I didn't factor in that props could be overwritten (oops). I might need to re-evaluate how I manage node ids!

DroidsWithStatelessComponent - I completely forgot about stateless components, whoops! I'll need to add support for this.

**Comment by oliverwoodings** [comment]
I've come up with a fix for the rest props thing. Check out #49 for info about stateless components - could do with your feedback!

**Comment by goncalvesjoao** [comment]
Cool, glad I could be of service. Waiting for that fix then ;)

**Comment by oliverwoodings** [comment]
@goncalvesjoao rc2 has been released, it should fix the rest props issue. Please give it a try :)

**Comment by oliverwoodings** [comment]
Actually rc2 might be broken... hold on

**Comment by oliverwoodings** [comment]
Ok released rc3 which fixes the bugs in rc1 + 2 (except stateless components)

**Comment by goncalvesjoao** [comment]
marvellous! thanks @oliverwoodings I'll close this issue, since #49 already addresses the same problem.
