### ISSUE TITLE
Stub/noop refs

### ISSUE THREAD

**Issue by oliverwoodings** [QubitProducts/react-test-tree#5]
I've come across a need to stub out or noop various children of a component. For example, say I have a high level view with children that load data; currently if I want to test the high level view I have to stub out the data loading of the children when in-fact I would much rather just not render the children at all and be done with it.

There are two problems to solve here:

__1. How do you 'configure' this in a clean way?__
One thought I had is a 'stub' tree:
```jsx
var Bar = React.createClass({
  render: function () {
    return (
      <div>
        <Baz ref="baz" />
      </div>
    );
  }
});

var FooBar = React.createClass({
  render: function () {
    return (
      <div>
        <Foo ref="foo" />
        <Bar ref="bar" />
      </div>
    );
  }
});

var stub = {
  foo: null,
  bar: {
    baz: FakeBaz
  }
};

testTree(<FooBar />, stub);
```
But is this too much - do we need to care about deep stubbing, or should we only allow stubbing refs at the root node level?

__2. How do we do this internally?__
This I haven't really thought about yet. Currently the tree is rendered by calling [renderIntoDocument](https://github.com/QubitProducts/react-test-tree/blob/master/lib/testTree.js#L6). We would need some kind of filtering process in order to stub out the refs at each class level. I'm wondering if it would be possible to recursively wrap the render methods of each ref in the stub tree?

@jhollingworth I would love your thoughts on this

**Comment by jhollingworth** [comment]
Would [shallow rendering](https://facebook.github.io/react/docs/test-utils.html#shallow-rendering) not give you most of the benefits but in a simpler way?

**Comment by oliverwoodings** [comment]
Already looked into it, but:

    Shallow testing currently has some limitations, namely not supporting refs.

**Comment by jhollingworth** [comment]
annoying! well the way you configure stubs makes sense. I have absolutely no idea how you'd implement this though...

**Comment by oliverwoodings** [comment]
Just spent a while trying to work this out. Needless to say it is pretty damn hard... I should be able to do it if I can find a way to intercept the render method of the element, however it is proving tricky to find.
