### ISSUE TITLE
bug: `children` is a function fail to propagate refs

### ISSUE THREAD

**Issue by joeybaker** [QubitProducts/react-test-tree#50]
I've run into a problem trying to test inside a redux `Provider` in react 0.13. React 0.14 allows redux to not use a function as the child, but this still feels like a legitimate use case that test tree should enable.

```js
testTree(<Provider store={store}>{ () => <MyComponent ref="hi" />}</Provider>) 
```

The above won't let you access the `'hi'` ref with test tree.

**Comment by jhollingworth** [comment]
Not 100% but I [think you can use `innerComponentRef` here](https://github.com/QubitProducts/react-test-tree#higher-order-components).

```
Provider.innerComponentRef = 'hi'
let tree = testTree(<Provider store={store}>{() => <MyComponent ref="hi" />}</Provider>)
expect(tree.somethingOnMyComponent).to.be.true
```

**Comment by oliverwoodings** [comment]
Yeah what @jhollingworth sounds about right. Your children are most likely not actually being returned by the Provider component and are being rendered by some lower level component which you don't have direct access to.

**Comment by joeybaker** [comment]
Got it. Thanks both. Would you accept a PR that clarified this in the docs?

**Comment by oliverwoodings** [comment]
Yep go for it! Make it against the react0.14 branch, thanks :)

**Comment by joeybaker** [comment]
Sorry to bring this, back up. I just got around to trying this on the 0.14 branch, and I'm not sure if I'm missing something.

Both of these tests fail to find the `'hi'` ref:

```jsx
test('works in fn', (t) => {
  class A extends React.Component {
    render () {
      return <div>{() => <div testRef="hi" />}</div>
    }
  }
  A.innerTestRef = 'hi'
  const tree = testTree(<A />)
  t.ok(tree.hi)
})

test('works hoc', (t) => {
  class A extends React.Component {
    render () {
      return <div>hi</div>
    }
  }
  const hoc = (Component) => React.createClass({
    render () {
      return <Component testRef="hi" />
    }
  })
  const withHoc = hoc(A)
  withHoc.innerTestRef = 'hi'
  const tree = testTree(<withHoc />)
  t.ok(tree.hi)
})
```

**Comment by joeybaker** [comment]
@oliverwoodings any thoughts on the above? ↑

**Comment by oliverwoodings** [comment]
@joeybaker i'm confused why `works hoc` fails given that there is a unit test already doing that kind of thing: https://github.com/QubitProducts/react-test-tree/blob/react0.14/test/testClassNodeTests.jsx#L144

**Comment by joeybaker** [comment]
@oliverwoodings `works hoc` failed b/c I was stupid, however `works in fn` still doesn't work :\

```jsx

test('works hoc', (t) => {
  class B extends React.Component {
    render () {
      return <div testRef="sup">hi</div>
    }
  }
  const hoc = (Component) => {
    return class HOC extends React.Component {
      render () {
        return React.createElement(Component, {testRef: 'hi'})
      }
    }
  }

  const WithHoc = hoc(B)
  WithHoc.innerTestRef = 'hi'
  const tree = testTree(<WithHoc />)

  t.ok(tree.get('sup')) // passes
  t.end()
})

test('works in fn', (t) => {
  class A extends React.Component {
    render () {
      return <div>{() => <div testRef="hi">hi</div>}</div>
    }
  }
  A.innerTestRef = 'hi'
  const tree = testTree(<A />)

  t.ok(tree.get('hi')) // fails
  t.end()
})
```

**Comment by oliverwoodings** [comment]
`works in fn` doesn't work because you are never actually calling that function. See https://discuss.reactjs.org/t/children-as-a-function-render-callbacks/626 for an example of how children-as-functions can be used. You need a HOC to actually call the function and return it from it's render function.

**Comment by joeybaker** [comment]
Doh! You're right of course. Thanks for pointing out my stupid!

**Comment by oliverwoodings** [comment]
@joeybaker for redux, you should look at the source and work out how the `Provider` is returning the contents. I suspect it will be returning the contents directly from it's render method. If so, your test refs will appear on the Provider itself so you should be able to access them like this:

```jsx
class A extends React.Component {
  render () {
    return <Provider testRef="foo">{() => <div testRef="bar">hi</div>}</Provider>
  }
}
let tree = testTree(<A />)
tree.getIn(["foo", "bar"])
```

`A` ends up being a sort of HoC for `Provider`. You could put an `innerTestRef` on `A` if all you care about is the contents returned by your child function.
