### ISSUE TITLE
[proposition] search nodes by using some kind of css selectors (search for a node with #id)

### ISSUE THREAD

**Issue by goncalvesjoao** [QubitProducts/react-test-tree#51]
#49 made me think that maybe something like the old school jQuery('#button1).click() way of doing things might solve the need of having DOM structure agnostic specs and the fact that Reat Components should be avoiding refs.

Something around these lines maybe:
```javascript
import React from 'react';
import sinon from 'sinon';
import testTree from 'react-test-tree';

const StatelessComponent = ({ onButton1, onButton2 }) => (
  <div>
    <button id="button1" onClick={ onButton1 } />
    <button id="button1" onClick={ onButton2 } />
  </div>
);

describe('StatelessComponent', () => {

  it('onButton1 and onButton2 props should be called according to their buttons', () => {
    const button1Spy = sinon.spy();
    const button2Spy = sinon.spy();

    const statelessComponent = testTree(<StatelessComponent onButton1={ button1Spy } onButton2={ button2Spy } />);

    statelessComponent.get('#button1').click();
    
    chai.expect(button1Spy.called).to.be.true;
    chai.expect(button2Spy.called).to.be.false;
  });

});
```

what do you guys think?

This way the designer team can mess around with the DOM structure, change the elements text, etc. and the specs won't break.

**Comment by oliverwoodings** [comment]
Have you seen [teaspoon](https://github.com/jquense/teaspoon)? Pretty similar to what you are talking about there. I don't think this kind of thing really comes under react-test-tree. Not disagreeing with the methodology about testing that way (it is something I am considering personally) but I won't be changing react-test-tree so much from it's original idea of working with a declarative tree.

**Comment by goncalvesjoao** [comment]
Sorry didn't know about teaspoon.
I agree with you completely @oliverwoodings you are right react-test-tree would suffer too big of a change and it would set a collision route with teaspoon.
